version: '3'
services:

  nginx:
    build: ./.docker/nginx-php
    restart: "no"
    depends_on:
      - php
    ports :
      - "${NGINX_PORT}:80"
    environment:
      - "SERVER_NAME=${SERVER_NAME}"
      - "PHP_ADDRESS=${PHP_ADDRESS}"
      - "TZ=${TIMEZONE}"
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - "ensiie"

  php:
    build:
      context: ./.docker/php-fpm/
      args:
        DOCKER_USER: ${DOCKER_USER}
        DOCKER_USER_ID: ${DOCKER_USER_ID}
    restart: "no"
    environment:
      TZ: ${TIMEZONE}
      XDEBUG_CONFIG: remote_host=${REMOTE_HOST}
      SSH_AUTH_SOCK: /ssh-agent
      DB_NAME: ${DB_USER}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www/html
      - $SSH_AUTH_SOCK:/ssh-agent
    working_dir: /var/www/html
    user: "${DOCKER_USER}"
    entrypoint:
      - ""
    command:
      - "php-fpm"
    networks:
      - "ensiie"

  postgres:
    build:
      context: ./.docker/postgres
    ports:
      - ${DB_PORT_EXTERNAL}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - "ensiie"

networks:
    ensiie:
        driver: bridge
